
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!


target 'MortgageCalculator_01' do

pod 'Alamofire'
pod 'Moya','15.0.0'
pod 'ReachabilitySwift','5.0.0'
pod 'Kingfisher'
pod 'SnapKit','5.0.1'
pod 'PermissionKit/Camera','1.4.2'
pod 'PermissionKit/Photos','1.4.2'
pod 'UIAdapter','1.0.0' # UI适配
pod 'EachNavigationBar','1.15.2'
pod 'SwiftDate','6.3.1' # 日期转换
pod 'FSPagerView','0.8.3' # banner
pod 'ZLPhotoBrowser','4.2.0'
pod 'EmptyDataSet-Swift','5.0.0'
pod 'SVProgressHUD','2.2.5'
pod 'Cache','6.0.0'
pod 'LEEAlert','1.5.1'
pod 'BRPickerView','2.7.6'
pod 'SnapKitExtend','1.1.0'
pod 'IQKeyboardManagerSwift', '6.5.9'
pod 'AttributedString','2.2.2'
pod 'SwipeCellKit','2.7.1'
pod 'FSTextView','1.8'
pod 'JXPhotoBrowser','3.1.3'
pod 'JKCountDownButton','1.3.0'
pod 'Closures','0.7'
pod 'CleanJSON','1.0.9'
pod 'SwiftyJSON','5.0.1'
pod 'BadgeHub'

# pod 'RAMAnimatedTabBarController'
# pod 'SkeletonView' # 骨架
# pod 'YBPopupMenu'
# pod "ESPullToRefresh" # 下拉刷新
# pod 'Loading'
# pod 'SwiftEntryKit'

end

